### ISSUE TITLE
Inconsistent presentation of source info in tree view

### ISSUE THREAD

**Issue by dhobern** [CatalogueOfLife/portal-components#24]
![image](https://user-images.githubusercontent.com/26148454/168497746-80d8d509-347c-4f11-b2ba-ff4381e15397.png)

Various issues with the way that sources are shown when the Info checkbox is selected:

1. Why do some of the sets of source datasets have only one dot/circle/bullet (see Fabales) while others have two (splitting the set into two groups - see Fabaceae)? Do the dots mean something? If so, should this be explained?
2. Why does the order appear differently in different cases (Fabales vs Fabaceae)?
3. Special bonus question - why does "World Plants" appear twice in some of these cases? I assume it represents multiple phases in the tree construction but it looks confusing.

I suggest removing the extra dot/circle/bullet where it appears and making sure that the list of sources does not include duplicates. Alphabetical order may also look tidier, unless there is a clear reason for one to be first (in which case, maybe consider making the most important one bold?).

**Comment by mdoering** [comment]
The last one after a bullet is only a single one ever and it means that very taxon, e.g. Fabaceae, is sourced from ILDIS while the former ones are sectors somewhere inside of Fabaceae. If there is no last one it means the taxon comes from the COL management hierarchy and is not sourced anywhere. 

In the case of duplicate World Plants this is because it is both the source of e.g. Curcubitales, but also provides other nested sectors. @dhobern @thomasstjerne if we think it is better I guess we can hide those nested sectors if the sectorKey of the taxon is already from the same source dataset?

There is no order given by the backend, it is in fact a map of datasetKeys to counts of sectors. @thomasstjerne the frontend could sort them either alphabetically or by number of sectors? I would go for alphabetical order since the number does not mean much really and its simpler to sort by the source title.
